from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.home_before_login,name='home_before_login'),
    path('login/',views.login,name='login'),
    # path('forgotpassword/',views.forgetpsswrd,name='forgetpsswrd'),
    # path('setnewtpsswrd/',views.setnewtpsswrd,name='setnewtpsswrd'),
    path('home/',views.home,name='home'),
    path('logout/',views.logout,name='logout'),
    path('menpage/',views.MenPage,name='MenPage'),
    path('signin/',views.signin,name='signin'),
    path('verify_otp/',views.verify_otp,name='verify_otp'),
    path('products/<int:product_id>/single_product_page/', views.single_product_page, name='single_product_page'),
    path('cart/add/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'), 
    path('cart/update/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
    path('add_address/', views.add_address, name='add_address'),
     path('checkout/', views.checkout, name='checkout'),
    path('order/create/', views.create_order, name='create_order'),
    path('order/confirmation/<str:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('profile/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('user_address/', views.user_address, name='user_address'),
    path('addresses/<int:address_id>/update/', views.update_address, name='update_address'),
    path('address/<int:address_id>/set-default/', views.set_default_address, name='set_default_address'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-reset-otp/<int:user_id>/', views.verify_reset_otp, name='verify_reset_otp'),
    path('reset-password/<int:user_id>/', views.reset_password, name='reset_password'),
    path('delete-address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/<str:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<str:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('orders/<str:order_id>/items/<int:item_id>/cancel/', views.cancel_order_item, name='cancel_order_item'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-cancelled/', views.payment_cancelled, name='payment_cancelled'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('wishlist-add-to-cart/', views.add_to_cart_from_wishlist, name='add_to_cart_from_wishlist'),
    path('wishlist/', views.wishlist_view, name='wishlist_view'),
    path('wishlist-remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wallet/dashboard/', views.wallet_dashboard, name='wallet_dashboard'),
    path('wallet/process-payment/', views.process_wallet_payment, name='process_wallet_payment'),
    path('wallet/process-refund/<int:order_id>/', views.process_refund_to_wallet, name='process_refund_to_wallet'),
    path('orders-<str:order_id>/return/', views.return_order, name='return_order'),
    
]