# Generated by Django 5.1.4 on 2025-02-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
