# Generated by Django 5.1.4 on 2025-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_usertable_email_otp_usertable_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
