# Generated by Django 5.1.4 on 2025-03-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usertable',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='gender',
        ),
    ]
