# Generated by Django 5.1.4 on 2025-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_alter_usertable_managers_remove_usertable_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
