# Generated by Django 5.1.4 on 2025-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_usertable_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
