# Generated by Django 5.1.4 on 2025-01-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0005_color_size_producttable_product_images_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='sale_Price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
