# Generated by Django 5.1.4 on 2025-02-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0010_alter_orderitem_product_alter_orderitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttable',
            name='Is_active',
        ),
    ]
