# Generated by Django 5.1.4 on 2025-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0012_remove_product_images_table_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
