# Generated by Django 5.1.4 on 2025-02-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0013_alter_producttable_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variancetable',
            name='Price',
        ),
    ]
