# Generated by Django 5.1.4 on 2025-02-22 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0015_wishilist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variancetable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='AdminProfile.producttable'),
        ),
    ]
