# Generated by Django 5.1.4 on 2025-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0018_returneditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
    ]
