# Generated by Django 5.1.4 on 2025-02-24 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0021_alter_offer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_till',
            field=models.DateField(),
        ),
    ]
