# Generated by Django 5.1.4 on 2025-02-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0025_order_coupon_applied_order_offer_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminProfile.offer'),
        ),
    ]
