# Generated by Django 5.1.4 on 2025-02-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0026_remove_order_offer_id_orderitem_offer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='offer_id',
            new_name='offer',
        ),
    ]
