# Generated by Django 5.1.4 on 2025-03-03 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0028_order_return_status_returnrequest_returnrequestitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='AdminProfile.order'),
        ),
    ]
