# Generated by Django 5.1.4 on 2025-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0031_orderitem_cancelation_reason_orderitem_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_payment_status',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_return_status',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
