# Generated by Django 5.1.4 on 2025-03-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0032_orderitem_item_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned'), ('PARTIALLY_RETURNED', 'Partially Returned')], default='PENDING', max_length=20),
        ),
    ]
