# Generated by Django 5.1.4 on 2025-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0036_remove_order_shipping_address_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
