# Generated by Django 5.1.4 on 2025-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0038_wallettransaction_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_category',
            field=models.CharField(choices=[('WALLET_OPERATION', 'Wallet Operation'), ('ORDER_CANCELLATION', 'Order Cancellation'), ('ORDER_RETURN', 'Order Return')], default='WALLET_OPERATION', max_length=20),
        ),
    ]
