# Generated by Django 5.1.4 on 2025-03-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0039_alter_wallettransaction_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
