# Generated by Django 5.1.4 on 2025-03-20 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProfile', '0040_alter_coupon_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('coupon_code',), name='unique_active_coupon_code'),
        ),
    ]
